### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/management-api#2]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by kwsutter** [comment]
Will be working with Jim Krueger to get these pipelines done for the Stable API project.   Still waiting for Jim's committership to come through...

**Comment by jim-krueger** [comment]
Jenkins Build CI/CD pipeline (first pass) is created (awaiting GPG and OSSRH Setup):

https://jenkins.eclipse.org/jakartaee-stable/job/Management-API%20master%20build/ (master build)
https://jenkins.eclipse.org/jakartaee-stable/job/Management-API_EE4J_8%20build/ (ee4j_8 build)

**Comment by jim-krueger** [comment]
[ERROR] Failed to execute goal org.glassfish.build:spec-version-maven-plugin:1.2:check-module (default) on project jakarta.management.j2ee-api: spec verification failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.glassfish.build:spec-version-maven-plugin:1.2:check-module (default) on project jakarta.management.j2ee-api: spec verification failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)

**Comment by m0mus** [comment]
@jim-krueger This is a known issue. We just released a new version of the spec-version plugin (1.5). See jakarta usage instructions here: https://github.com/javaee/spec-version-maven-plugin/pull/5

**Comment by jim-krueger** [comment]
Thanks @m0mus , that resolved that.   I still have the following on all of the stable projects, but I'm assuming that will be resolved when the OSSRH and GPG Setup is completed on these projects?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project jakarta.management.j2ee-api: Exit code: 2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project jakarta.management.j2ee-api: Exit code: 2
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)

**Comment by jim-krueger** [comment]
spec-version-maven issue fixed under #9

**Comment by m0mus** [comment]
@jim-krueger It looks like some gpg configuration is wrong. It could be related to the instance configuration. I am suggesting raising a BugZilla ticket to webmasters.

**Comment by jim-krueger** [comment]
@m0mus Thanks,  https://bugs.eclipse.org/bugs/show_bug.cgi?id=539619

**Comment by jim-krueger** [comment]
@m0mus I chose Product: "Jakartaee-stable" and Component "General".... hopefully it will get flagged to the webmasters.

**Comment by jim-krueger** [comment]
Jenkin CI/CD build jobs are now green, closing issue:

https://jenkins.eclipse.org/jakartaee-stable/job/Management-API%20master%20build/
https://jenkins.eclipse.org/jakartaee-stable/job/Management-API_EE4J_8%20build/
